# Generated by Django 5.2.15 on 2026-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_publisher_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
