# Generated by Django 5.2.15 on 2026-07-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0003_author_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='my_first_app.author'),
        ),
    ]
