# Generated by Django 5.2.15 on 2026-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='websit',
            new_name='website',
        ),
    ]
